spring:
  name: shopease
  datasource:
    url: jdbc:postgresql://localhost:5432/shopease
    username: postgres
    password: Thanhtam2004.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect